### PR TITLE
Add notebook for static plotting

### PR DESCRIPTION
**Pull request by timtreis**
Needs more examples with other data - datasets tbd

### CODE REVIEW

**Comment by LucaMarconato** [comment]
The notebook looks great!

Code review:
- [x] I'd add `%load_ext jupyter_black`
- [ ] table of content: appears to be broken; I'd maybe consider removing it and use the TOC view from `jupyter-lab` during the workshop. 
- [x] from the hackmd it's the notebook number 5, so I'd rename to `nb5`
- ~I'd add a cell a call to the downloader to get the merfish data: `python download.py zarr merfish data`~ actually no, I am editing the readme to explain how to download the data beforehand.
- [x] minor: in `sdata_merfish.pl.render_shapes().pl.show()  # visualises the two shapes on top of each other since they exist in the same coordinate system "global"`, I'd add the comment before the calls so the line is shorter and it's easier to read
- [x] minor: same for `sdata_merfish["single_molecule"].compute() # this is a dask dataframe, so we need to call compute to get the actual data`

**Comment by LucaMarconato** [comment]
- [ ] in the transformations section, I'd add a new coordinate system so we can show that:
	- [ ] by default spatialdata-plot shows all the coordinate systems. In this way the two alignments can be appreciated next to each other. 
	- [ ] btw, I'd make the plot zoomed in so that the difference is better seen
	- [ ] we can use `pl.show(coordinate_systems)` to choose what to show
	- [ ] last sentence (this one `Generally, the ... for example like this:`). I find the sentence not super clear, maybe we can say that we don't support `pl.spatial(color=['gene_a', 'gene_b', 'gene_c'])` and instead we recommend to split the plot into multiple axes as shown.

**Comment by LucaMarconato** [comment]
Also
- [x] conda vs pip?
```
    - spatialdata==0.2.2
    - spatialdata-plot
    - spatialdata-io
    - napari-spatialdata
```
are all available via `conda`, on the other hand installing everything via `pip` would be faster, so I'd choose that route if we end up using colab. I'd keep using jupyter locally for the moment, so l'd go fully conda.

**Comment by timtreis** [comment]
>  table of content: appears to be broken; I'd maybe consider removing it and use the TOC view from jupyter-lab during the workshop.

works on my machine 🤡 How do you call it? Theoretically that TOC is just HTML links so it should work fairly robustly (maybe outside of the GitHub code viewer?)

>  conda vs pip?

Happy to go full conda, I think local is less failure-prone than collab also. Always hard to anticipate the technical skill level of the users. I think it'll just be good to lock down certain major things, like the Python version and our ecosystem packages

**Pull request merged**
